### ISSUE TITLE
Update `schema.prisma` default path

### ISSUE THREAD

**Issue by ravshansbox** [omar-dulaimi/prisma-schema-sorter#6]
- **I'm submitting a ...**
  [x] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
The default path for schema file should be `./schema.prisma` rather than `./prisma/schema.prisma`

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by omar-dulaimi** [comment]
Hey @ravshansbox 

The Prisma schema almost always resides in the `prisma` folder as you can see in [Prisma Examples Repo](https://github.com/prisma/prisma-examples). So it only makes sense to keep the path as is; since running commands tends to happen inside the root of a project.

Though you can easily change the command to work based on your project structure. You're welcomed to make contributions to this project or to any of my other projects, anytime. Just that this PR won't be merged.

Thank you
